0.07.01 to catch error and destroy GTU when the error takes place:
GTU 1169305 does not have a reference lane with pos between 0 and length...
GTU 1169305: Bad interval (253.0585503827547..253.03161857759991; length of this OTSLine3D is 253.03161857759991)
Lane A1 of L25a, len=253.031619m
253.058550m
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at nl.tudelft.simulation.dsol.formalisms.eventscheduling.SimEvent.execute(SimEvent.java:113)
        at nl.tudelft.simulation.dsol.simulators.DEVSRealTimeClock.run(DEVSRealTimeClock.java:189)
        at nl.tudelft.simulation.language.concurrent.WorkerThread.run(WorkerThread.java:90)
Caused by: org.opentrafficsim.core.gtu.GTUException: org.opentrafficsim.core.geometry.OTSGeometryException: Bad interval (253.0585503827547..253.03161857759991; length of this OTSLine3D is 253.0316185
7759991)
        at org.opentrafficsim.road.gtu.lane.tactical.AbstractLaneBasedTacticalPlanner.buildLaneListForward(AbstractLaneBasedTacticalPlanner.java:163)
        at org.opentrafficsim.road.gtu.lane.tactical.AbstractLaneBasedTacticalPlanner.buildLaneListForward(AbstractLaneBasedTacticalPlanner.java:115)
        at org.opentrafficsim.road.gtu.lane.tactical.AbstractLaneBasedTacticalPlanner.buildLaneListForward(AbstractLaneBasedTacticalPlanner.java:98)
        at org.opentrafficsim.road.gtu.lane.tactical.LaneBasedGTUFollowingChange0TacticalPlanner.generateOperationalPlan(LaneBasedGTUFollowingChange0TacticalPlanner.java:118)
        at org.opentrafficsim.core.gtu.AbstractGTU.move(AbstractGTU.java:182)
        at org.opentrafficsim.road.gtu.lane.AbstractLaneBasedGTU.move(AbstractLaneBasedGTU.java:298)
        ... 6 more
Caused by: org.opentrafficsim.core.geometry.OTSGeometryException: Bad interval (253.0585503827547..253.03161857759991; length of this OTSLine3D is 253.03161857759991)
        at org.opentrafficsim.core.geometry.OTSLine3D.extract(OTSLine3D.java:461)
        at org.opentrafficsim.core.geometry.OTSLine3D.extract(OTSLine3D.java:445)
        at org.opentrafficsim.road.gtu.lane.tactical.AbstractLaneBasedTacticalPlanner.buildLaneListForward(AbstractLaneBasedTacticalPlanner.java:150)
        ... 11 more
nl.tudelft.simulation.dsol.SimRuntimeException: java.lang.reflect.InvocationTargetException
        at nl.tudelft.simulation.dsol.formalisms.eventscheduling.SimEvent.execute(SimEvent.java:119)
        at nl.tudelft.simulation.dsol.simulators.DEVSRealTimeClock.run(DEVSRealTimeClock.java:189)
        at nl.tudelft.simulation.language.concurrent.WorkerThread.run(WorkerThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at nl.tudelft.simulation.dsol.formalisms.eventscheduling.SimEvent.execute(SimEvent.java:113)
        ... 2 more
Caused by: org.opentrafficsim.core.gtu.GTUException: org.opentrafficsim.core.geometry.OTSGeometryException: Bad interval (253.0585503827547..253.03161857759991; length of this OTSLine3D is 253.0316185
7759991)
        at org.opentrafficsim.road.gtu.lane.tactical.AbstractLaneBasedTacticalPlanner.buildLaneListForward(AbstractLaneBasedTacticalPlanner.java:163)
        at org.opentrafficsim.road.gtu.lane.tactical.AbstractLaneBasedTacticalPlanner.buildLaneListForward(AbstractLaneBasedTacticalPlanner.java:115)
        at org.opentrafficsim.road.gtu.lane.tactical.AbstractLaneBasedTacticalPlanner.buildLaneListForward(AbstractLaneBasedTacticalPlanner.java:98)
        at org.opentrafficsim.road.gtu.lane.tactical.LaneBasedGTUFollowingChange0TacticalPlanner.generateOperationalPlan(LaneBasedGTUFollowingChange0TacticalPlanner.java:118)
        at org.opentrafficsim.core.gtu.AbstractGTU.move(AbstractGTU.java:182)
        at org.opentrafficsim.road.gtu.lane.AbstractLaneBasedGTU.move(AbstractLaneBasedGTU.java:298)
        ... 6 more
Caused by: org.opentrafficsim.core.geometry.OTSGeometryException: Bad interval (253.0585503827547..253.03161857759991; length of this OTSLine3D is 253.03161857759991)
        at org.opentrafficsim.core.geometry.OTSLine3D.extract(OTSLine3D.java:461)
        at org.opentrafficsim.core.geometry.OTSLine3D.extract(OTSLine3D.java:445)
        at org.opentrafficsim.road.gtu.lane.tactical.AbstractLaneBasedTacticalPlanner.buildLaneListForward(AbstractLaneBasedTacticalPlanner.java:150)
        ... 11 more