made change in SimulatorChangeTransceiver due to weird compilation error:
opentrafficsim/workspace/ots-sim0mq/src/main/java/org/opentrafficsim/sim0mq/publisher/SimulatorStateTransceiver.java:[139,9] no suitable method found for fireTimedEvent(org.djutils.event.TimedEventType,boolean,capture#1 of ?)
    method org.djutils.event.EventProducer.<C>fireTimedEvent(org.djutils.event.TimedEvent<C>) is not applicable
      (cannot infer type-variable(s) C
        (actual and formal argument lists differ in length))
    method org.djutils.event.EventProducer.<C>fireTimedEvent(org.djutils.event.TimedEventType,java.io.Serializable,C) is not applicable
      (inference variable C has incompatible bounds
        equality constraints: capture#2 of ?
        lower bounds: java.lang.Object&java.lang.Comparable<capture#2 of ?>&java.io.Serializable)
    method org.djutils.event.EventProducer.<C>fireTimedEvent(org.djutils.event.TimedEventType,byte,C) is not applicable
      (cannot infer type-variable(s) C
        (argument mismatch; boolean cannot be converted to byte))
    method org.djutils.event.EventProducer.<C>fireTimedEvent(org.djutils.event.TimedEventType,char,C) is not applicable
      (cannot infer type-variable(s) C
        (argument mismatch; boolean cannot be converted to char))
    method org.djutils.event.EventProducer.<C>fireTimedEvent(org.djutils.event.TimedEventType,boolean,C) is not applicable
      (inference variable C has incompatible bounds
        equality constraints: capture#2 of ?
        lower bounds: java.lang.Object&java.lang.Comparable<capture#2 of ?>&java.io.Serializable)
    method org.djutils.event.EventProducer.<C>fireTimedEvent(org.djutils.event.TimedEventType,double,C) is not applicable
      (cannot infer type-variable(s) C
        (argument mismatch; boolean cannot be converted to double))
    method org.djutils.event.EventProducer.<C>fireTimedEvent(org.djutils.event.TimedEventType,int,C) is not applicable
      (cannot infer type-variable(s) C
        (argument mismatch; boolean cannot be converted to int))
    method org.djutils.event.EventProducer.<C>fireTimedEvent(org.djutils.event.TimedEventType,long,C) is not applicable
      (cannot infer type-variable(s) C
        (argument mismatch; boolean cannot be converted to long))
    method org.djutils.event.EventProducer.<C>fireTimedEvent(org.djutils.event.TimedEventType,short,C) is not applicable
      (cannot infer type-variable(s) C
        (argument mismatch; boolean cannot be converted to short))
    method org.djutils.event.EventProducer.<C>fireTimedEvent(org.djutils.event.TimedEventType,float,C) is not applicable
      (cannot infer type-variable(s) C
        (argument mismatch; boolean cannot be converted to float))